AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Heimdall-Burstable-SES

Globals:
    Function:
        Timeout: 3

Resources:
    EmailWaitingQueue:
        Type: AWS::SQS::Queue
    SendEmailFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./
            Handler: app.lambdaHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                EmailWaitingQueueEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt EmailWaitingQueue.Arn
                        BatchSize: 1
                        ScalingConfig:
                            MaximumConcurrency: 1
            Policies:
                - AmazonSESFullAccess
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - app.ts

Outputs:
    SendEmailFunctionFunction:
        Description: 'SendEmailFunction Lambda ARN'
        Value: !GetAtt SendEmailFunctionFunction.Arn
    SendEmailFunctionFunctionIamRole:
        Description: 'Implicit IAM Role created for SendEmailFunction'
        Value: !GetAtt SendEmailFunctionFunctionRole.Arn
