name: Cleanup

on:
  pull_request:
    branches: ['**']
    types:
      - closed

jobs:
  delete-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{env.OIDC_ROLE }}
          aws-region: ${{ env.TESTING_REGION }}

      - name: Delete feature branch stack
        run: |
          sam delete \
            --stack-name $(echo "${PROJECT_INITIALS}-${{github.head_ref}}" | tr -cd '[a-zA-Z0-9-]') \
            --region ${TESTING_REGION} \
            --no-prompts
