name: Cleanup

on:
  pull_request:
    branches: ['**']
    types:
      - closed

env:
  TESTING_REGION: eu-central-1

jobs:
  delete-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.TESTING_REGION }}

      - name: Delete feature branch stack
        run: |
          sam delete \
            --stack-name $(echo "${{github.head_ref}}" | tr -cd '[a-zA-Z0-9-]' | sed 's/^[^a-zA-Z]*/a/') \
            --region ${TESTING_REGION} \
            --no-prompts
