name: Deploy Feature

on:
  pull_request:
    branches: ['**']
    types: [labeled, opened, reopended, synchronize]

env:
  SAM_TEMPLATE: template.yaml
  TESTING_REGION: eu-central-1
  ROLE: arn:aws:iam::055198341417:oidc-provider/token.actions.githubusercontent.com

jobs:
  build-and-deploy-feature:
    if: contains( github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: MySessionName
          role-to-assume: arn:aws:iam::055198341417:role/Github-OIDC-Role-ANXAAI1WA8V2
          aws-region: ${{ env.TESTING_REGION }}

      - name: Deploy to feature stack
        shell: bash
        run: |
          sam deploy --stack-name $(echo "${{github.head_ref}}" | tr -cd '[a-zA-Z0-9-]' | sed 's/^[^a-zA-Z]*/a/') \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset
