name: Deploy Production

on:
  push:
    branches:
      - 'main'

env:
  PROD_STACK_NAME: production-stack

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template "template.yaml" --use-container

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{vars.OIDC_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}

      - name: Deploy production stack
        run: |
          sam deploy --stack-name $(echo "${{PROJECT_INITIALS}}-${{PROD_STACK_NAME}}" | tr -cd '[a-zA-Z0-9-]') \
            --capabilities CAPABILITY_IAM \
            --region ${{vars.AWS_REGION}} \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset
