name: Deploy Feature

on:
  pull_request:
    branches: ['**']
    types: [labeled, opened, reopended, synchronize]

jobs:
  build-and-deploy-feature:
    if: contains( github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template "template.yaml" --use-container

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{vars.OIDC_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}

      - name: Deploy feature stack
        shell: bash
        run: |
          sam deploy --stack-name $(echo "${{PROJECT_INITIALS}}-${{github.head_ref}}" | tr -cd '[a-zA-Z0-9-]') \
            --capabilities CAPABILITY_IAM \
            --region ${{vars.AWS_REGION}} \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset
