name: Deploy

on:
  pull_request:
    branches: ['**']
    types: [labeled, opened, reopended, synchronize]

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  TESTING_STACK_NAME: development-stack
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::055198341417:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-17JI9W41F4I6S
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::055198341417:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1KGR6DZC0VLB2
  TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-dev-pipeline-artifactsbucket-1hhmtax6751pk
  TESTING_REGION: eu-central-1

jobs:
  build-and-deploy-feature:
    if: contains( github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to feature stack in the testing account
        shell: bash
        run: |
          sam deploy --stack-name $(echo "${{github.head_ref}}" | tr -cd '[a-zA-Z0-9-]' | sed 's/^[^a-zA-Z]*/a/') \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE} \
            --no-confirm-changeset
